#!/bin/bash -e

if [ "$1" = "" ]; then
  echo "Please specify Go compiler version (e.g go1.12beta1)"
  exit 1
fi

if [ "$1" = "list" ]; then
  find $HOME/go/bin/go1* | cut -d"/" -f6
  exit 0
fi

if [ "$1" = "download" ]; then
  go get golang.org/dl/$2
  $2 download
  echo "Download $2 succeeded"
  exit 0
fi

if [ "$1" = "releases" ]; then
  curl -v --silent -X GET https://api.github.com/repos/golang/go/git/refs/tags 2>&1 |
    grep tags | grep url | grep -v weekly | grep -v release | cut -d"/" -f10 | sed 's/",//' | tail -n 15 | tac
  exit 0
fi

GO="$HOME/go/bin/$1"

if [ ! -x "$GO" ]; then
  echo "Failed to switch Go compiler. $GO is not Go compiler"
  exit 1
fi

echo "Use $GO as Go compiler"
rm -f $HOME/go/bin/go
ln -s $GO $HOME/go/bin/go
